### ISSUE TITLE
3.0.0: pytest warnings

### ISSUE THREAD

**Issue by kloczek** [testing-cabal/fixtures#48] opened 2021-05-05 06:54 UTC
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-fixtures-3.0.0-23.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-fixtures-3.0.0-23.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/python3 -Bm pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.9, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: /home/tkloczko/rpmbuild/BUILD/fixtures-3.0.0
plugins: forked-1.3.0, shutil-1.7.0, virtualenv-1.7.0, asyncio-0.14.0, expect-1.1.0, cov-2.11.1, mock-3.5.1, httpbin-1.0.0, xdist-2.2.1, flake8-1.0.7, timeout-1.4.2, betamax-0.8.1, pyfakefs-4.4.0, freezegun-0.4.2, cases-3.4.6, hypothesis-6.10.1, case-1.5.3, isort-1.3.0, aspectlib-1.5.2, flaky-3.7.0
collected 130 items

fixtures/tests/test_callmany.py ...                                                                                                                                  [  2%]
fixtures/tests/test_fixture.py ...........................                                                                                                           [ 23%]
fixtures/tests/test_testcase.py ....                                                                                                                                 [ 26%]
fixtures/tests/_fixtures/test_environ.py ........                                                                                                                    [ 32%]
fixtures/tests/_fixtures/test_logger.py .............                                                                                                                [ 42%]
fixtures/tests/_fixtures/test_mockpatch.py ......                                                                                                                    [ 46%]
fixtures/tests/_fixtures/test_monkeypatch.py ...........ss................                                                                                           [ 69%]
fixtures/tests/_fixtures/test_packagepath.py ..                                                                                                                      [ 70%]
fixtures/tests/_fixtures/test_popen.py ...........                                                                                                                   [ 79%]
fixtures/tests/_fixtures/test_pythonpackage.py ...                                                                                                                   [ 81%]
fixtures/tests/_fixtures/test_pythonpath.py ..                                                                                                                       [ 83%]
fixtures/tests/_fixtures/test_streams.py .......                                                                                                                     [ 88%]
fixtures/tests/_fixtures/test_tempdir.py .......                                                                                                                     [ 93%]
fixtures/tests/_fixtures/test_temphomedir.py ..                                                                                                                      [ 95%]
fixtures/tests/_fixtures/test_timeout.py ...                                                                                                                         [ 97%]
fixtures/tests/_fixtures/test_warnings.py ...                                                                                                                        [100%]

============================================================================= warnings summary =============================================================================
../../../../../usr/lib64/python3.8/unittest/case.py:26
  /usr/lib64/python3.8/unittest/case.py:26: PytestCollectionWarning: cannot collect test class 'SkipTest' because it has a __init__ constructor (from: fixtures/tests/_fixtures/test_timeout.py)
    class SkipTest(Exception):

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================================= short test summary info ==========================================================================
SKIPPED [1] fixtures/tests/_fixtures/test_monkeypatch.py:217: Fails with Python 3.9
SKIPPED [1] fixtures/tests/_fixtures/test_monkeypatch.py:185: Fails with Python 3.9
================================================================ 128 passed, 2 skipped, 1 warning in 2.42s =================================================================
+ /usr/bin/python3 -m testtools.run fixtures.test_suite
/usr/lib64/python3.8/runpy.py:127: RuntimeWarning: 'testtools.run' found in sys.modules after import of package 'testtools', but prior to execution of 'testtools.run'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Tests running...

Ran 128 tests in 2.031s
```

**Comment by jelmer** [comment] 2021-12-27 02:22
SkipTest is not a test class; why does pytest think it is?

**Comment by kloczek** [comment] 2021-12-27 02:23
No idea .. :/
I'm using pytest 6.2.5.

**Comment by jelmer** [comment] 2021-12-27 02:34
Closing in that case; I don't think this is worth pursuing unless you're actually seeing problems from this.

**Closed** 2021-12-27 02:33 UTC

**Comment by rbtcollins** [comment] 2021-12-27 07:30
@kloczek I think its worth noting - the packages you're filing these bugs on don't use pytest. Its not a bug that they don't work with it. It is, perhaps, a missing feature - but since your goal is packaging things, I have to ask - why don't you use the test runner that upstream uses for these packages?

**Comment by kloczek** [comment] 2021-12-27 07:46
Because testing exact package is not only about that package.
It is alse about testing all other components involved in exct test suite.
More tests than higher probablity that sometbing will be catched  on testing stage :)

I understand why this ticket has been closed.
As I see during packaging even warnings it is IMO always better to ask than ignore something :P

Thank you for your time :)

**Comment by rbtcollins** [comment] 2021-12-27 08:04
Running pytest rather than the correct runner will *cause* errors and warnings. It is not testing more, it is running the tests in pytests 'compat' shim, not a complete match for unittest. Not saying its bad, its just has subtle differences, and the test extensions in use testing-cabal projects expose those difference.
